services:
  auth-db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - authentication:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
          
  auth-service:
      build: WordleBattle.Auth.Api
      restart: unless-stopped
      environment:
        ConnectionStrings__AuthDb: Host=auth-db;Port=${DB_PORT};Database=${DB_NAME};Username={DB_USER};Password=${DB_PASSWORD}
      depends_on:
        auth-db:
          condition: service_healthy
      ports:
        - "5000:8080"
      deploy:
        resources:
          limits:
            cpus: "1"
            memory: 1G
    
volumes:
  authentication: 